### ISSUE TITLE
0/18 byte files in replay folder

### ISSUE THREAD

**Issue by Norup123** [GoSecure/pyrdp#169]
Is there a way to stop it from making replay files and the player tabs on every scan? It makes it rather difficult to sort through.

**Comment by Res260** [comment]
We had a feature where empty files were deleted, has there been a regression? 🤔

**Comment by Norup123** [comment]
Oh shit, maybe i just need to update, cool.
I´ll try that out

**Comment by Res260** [comment]
Report back if it works, if it doesnt tell us if the files are actually empty, or very small!

**Comment by Norup123** [comment]
So i did a git pull, and it looks like im not getting any 0b files, but it still makes an 18byte file for every connection

**Comment by Res260** [comment]
I *think* that 18 bytes files are not simple SYN/SYNACK/ACK scans, but service scans, where the first RDP packet is sent to make sure the destination is an RDP server. Packet capture analysis could confirm that....

If it is the case, I'm not sure that we want to delete those files 🤔 

@obilodeau thoughts?

**Comment by obilodeau** [comment]
The 0 bytes ones should probably not be created but the 18 bytes ones might be interesting to dig deeper into what is going on.

> We had a feature where empty files were deleted, has there been a regression? :thinking:

Quickly grepping the codebase for `unlink` (python's delete api) and `delete` didn't lead to code handling those empty sessions... There is downloaded file deduplication (deleting on same hash) but not empty session deletion AFAICT.

So to me, this is two issues:

a. interactive player should open tab only when something was recorded (session logs should still be session logs, any non-zero log is interesting)
b. why do we have a lot of these 0 / 18 bytes sessions, that should be investigated

For either issue, I need to be able to reproduce the problem locally. @Norup123 can you provide a pcap or are you willing to wait until I get similar traffic in my honeypots?

**Comment by Res260** [comment]
I implemented that feature last year, but I think it got removed when @xshill did the big refactor:
https://github.com/GoSecure/pyrdp/commit/bf27f03a72c1e16c02b409f0b7441e9a5f0a3b87

**Comment by Norup123** [comment]
#158 trying to make a tcpdump for this. Havnt been able to capture the error in the other issue in the dump im currently making, but the error appeared right before i started, so hoping it will show again.

My /replay folder is FILLED with 0 or 18 byte files.
And still not a single attacker/bot has gone past the certificate error =/

**Comment by Norup123** [comment]
[tcpdump.zip](https://github.com/GoSecure/pyrdp/files/3896476/tcpdump.zip)

**Comment by Norup123** [comment]
Currently getting these errors in my logs for every entry, and i cant get past the initial loading when i try to connect with rdp 
![image](https://user-images.githubusercontent.com/54578187/69718244-28350880-110e-11ea-8966-d15a9988ace4.png)

**Comment by Norup123** [comment]
i may or may not have found my issue with the breaking. Could have been the windows machine, going on standby...

**Comment by alxbl** [comment]
As far as the player tabs are concerned, we could auto-close all tabs that last less than N seconds and all tabs that receive no data but are not disconnected after a long enough period of time.

The former would take care of scanners, while the latter would take care of "hung" connections that we have been seeing in some cases.

Alternatively, I'm pretty sure in either cases we never get far enough in the connection sequence to get video, so tabs that never made it to connection established after N seconds could be closed automatically. This approach would be cleaner.

**Comment by alxbl** [comment]
I suggest to track the tab creation issue in #142, and use this issue to track the small replay files.
